### PR TITLE
Bump signalhub module version number

### PR DESCRIPTION
**Pull request by kevzettler**

### CODE REVIEW

**Comment by emilbayes** [comment]
@kevzettler Are you actively using this image? :) I wanted to bump both signalhub and the node version, but don't really know what base image is up to date with node 8

**Comment by kevzettler** [comment]
@emilbayes yeah I am actively using it. I can bump the base image as well.

**Comment by kevzettler** [comment]
@emilbayes I added a commit that bumps the bade Node image to the official docker/node image and node 9.

I have tested `build` a `run` and it looks good

**Comment by emilbayes** [comment]
Cool :) I'll give you commit rights as well

**Pull request merged**
